users_search = 'https://api.twitter.com/1.1/users/search.json?q={q}&&page={page}&&count={count}&&include_entities={include_entities}'
followers_list = 'https://api.twitter.com/1.1/followers/list.json?screen_name={screen_name}&cursor={cursor}&count={count}'
followering_list = 'https://api.twitter.com/1.1/friends/list.json?screen_name={screen_name}&cursor={cursor}&count={count}'
user_timeline = 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name={screen_name}&count={count}&max_id={max_id}'
home_page = 'https://twitter.com/{screen_name}'

timeline = 'https://api.twitter.com/2/timeline/profile/{user_id}.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cards_platform={cards_platform}&include_cards={include_cards}&include_composer_source={include_composer_source}&include_ext_alt_text={include_ext_alt_text}&include_reply_count={include_reply_count}&tweet_mode={tweet_mode}&include_entities={include_entities}&include_user_entities={include_user_entities}&include_ext_media_color={include_ext_media_color}&include_ext_media_availability={include_ext_alt_text}&send_error_codes={send_error_codes}&simple_quoted_tweets={simple_quoted_tweets}&include_tweet_replies={include_tweet_replies}&userId={userId}&count={count}&cursor={cursor}&ext={ext}'
friends = 'https://api.twitter.com/1.1/friends/following/list.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cursor={cursor}&user_id={user_id}&count={count}&with_total_count={with_total_count}'
followers = 'https://api.twitter.com/1.1/followers/list.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cursor={cursor}&user_id={user_id}&count={count}'
replies = 'https://api.twitter.com/2/timeline/conversation/{twitter_id}.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cards_platform={cards_platform}&include_cards={include_cards}&include_composer_source={include_composer_source}&include_ext_alt_text={include_ext_alt_text}&include_reply_count={include_reply_count}&tweet_mode={tweet_mode}&include_entities={include_entities}&include_user_entities={include_user_entities}&include_ext_media_color={include_ext_media_color}&include_ext_media_availability={include_ext_media_availability}&send_error_codes={send_error_codes}&simple_quoted_tweets={simple_quoted_tweets}&count={count}&cursor={cursor}&ext={ext}'
retweeted_by = 'https://api.twitter.com/2/timeline/retweeted_by.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cards_platform={cards_platform}&include_cards={include_cards}&include_composer_source={include_composer_source}&include_ext_alt_text={include_ext_alt_text}&include_reply_count={include_reply_count}&tweet_mode={tweet_mode}&include_entities={include_entities}&include_user_entities={include_user_entities}&include_ext_media_color={include_ext_media_color}&include_ext_media_availability={include_ext_media_availability}&send_error_codes={send_error_codes}&simple_quoted_tweets={simple_quoted_tweets}&tweet_id={tweet_id}&count={count}&ext={ext}'
liked_by = 'https://api.twitter.com/2/timeline/liked_by.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cards_platform={cards_platform}&include_cards={include_cards}&include_composer_source={include_composer_source}&include_ext_alt_text={include_ext_alt_text}&include_reply_count={include_reply_count}&tweet_mode={tweet_mode}&include_entities={include_entities}&include_user_entities={include_user_entities}&include_ext_media_color={include_ext_media_color}&include_ext_media_availability={include_ext_media_availability}&send_error_codes={send_error_codes}&simple_quoted_tweets={simple_quoted_tweets}&tweet_id={tweet_id}&count={count}&ext={ext}'
search = 'https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type={include_profile_interstitial_type}&include_blocking={include_blocking}&include_blocked_by={include_blocked_by}&include_followed_by={include_followed_by}&include_want_retweets={include_want_retweets}&include_mute_edge={include_mute_edge}&include_can_dm={include_can_dm}&include_can_media_tag={include_can_media_tag}&skip_status={skip_status}&cards_platform={cards_platform}&include_cards={include_cards}&include_composer_source={include_composer_source}&include_ext_alt_text={include_ext_alt_text}&include_reply_count={include_reply_count}&tweet_mode={tweet_mode}&include_entities={include_entities}&include_user_entities={include_user_entities}&include_ext_media_color={include_ext_media_color}&include_ext_media_availability={include_ext_media_availability}&send_error_codes={send_error_codes}&simple_quoted_tweets={simple_quoted_tweets}&q={q}&count={count}&query_source={query_source}&pc={pc}&spelling_corrections={spelling_corrections}&ext={ext}';
